### PR TITLE
Added Azure CLI to the list of repos

### PR DESCRIPTION
**Pull request by ggailey777**

### CODE REVIEW

**Comment by paulbatum** [comment]
@ggailey777 Its already in the list. Its called core tools:

See:
```
|Core Tools|Command line interface for local development|[File an Issue](https://github.com/Azure/azure-functions-core-tools/issues)|
```

**Comment by ggailey777** [comment]
Isn’t that just Core Tools? What if people want to file issues on az functionapp?

**Comment by fabiocav** [comment]
@ggailey777 closing this since there hasn't been any activity. Please reopen if needed.

**Comment by paulbatum** [comment]
@fabiocav this PR makes sense, I misunderstood it originally. Can we just merge?

**Comment by fabiocav** [comment]
Done.

**Pull request merged**
